const CUSTOMER_ID_KEY="cacho-customer-id-v1";
function getCustomerId(){try{let id=localStorage.getItem(CUSTOMER_ID_KEY);if(!id){id=crypto?.randomUUID?.()||`cust-${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(CUSTOMER_ID_KEY,id)}return id}catch{return ""}}
function money(v){return `₱${Number(v||0).toLocaleString("en-PH",{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function esc(v){return String(v||"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
function close(){document.getElementById("cacho-my-orders-modal")?.remove();document.body.style.overflow=""}
async function render(){
 const modal=document.createElement("div");modal.id="cacho-my-orders-modal";modal.className="customer-orders-backdrop";modal.innerHTML=`<div class="customer-orders-modal"><button class="customer-orders-close" type="button">×</button><div class="customer-orders-head"><span>MY ORDERS</span><h2>Your order history</h2><p>See what you ordered and the latest status, including completed orders.</p></div><div class="customer-orders-empty"><p>Loading your orders…</p></div></div>`;document.body.appendChild(modal);document.body.style.overflow="hidden";modal.querySelector(".customer-orders-close").onclick=close;modal.addEventListener("click",e=>{if(e.target===modal)close()});
 try{const r=await fetch(`/api/orders?customerId=${encodeURIComponent(getCustomerId())}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load orders");const orders=Array.isArray(d.orders)?d.orders:[];const cards=orders.map(o=>`<article class="customer-order-card"><div class="customer-order-top"><div><strong>${esc(o.customer?.name||"My order")}</strong><small>${new Date(o.createdAt).toLocaleString("en-PH")}</small></div><span class="customer-status">${esc(o.status||"NEW")}</span></div><div class="customer-order-products">${(o.items||[]).map(i=>`<div><span>${esc(i.productName)} × ${Number(i.quantity||0)}</span><b>${money(i.lineTotal)}</b></div>`).join("")}</div><div class="customer-order-total"><span>Total</span><b>${money(o.total)}</b></div></article>`).join("");modal.querySelector(".customer-orders-modal").insertAdjacentHTML("beforeend",cards||`<div class="customer-orders-empty"><strong>No orders yet.</strong><p>Your submitted wholesale orders will appear here.</p></div>`);modal.querySelector(".customer-orders-empty")?.remove()}catch(err){modal.querySelector(".customer-orders-empty").innerHTML=`<strong>Couldn't load your orders.</strong><p>${esc(err.message)}</p>`}
}
async function updateCount(){const el=document.getElementById("cacho-orders-count");if(!el)return;try{const r=await fetch(`/api/orders?customerId=${encodeURIComponent(getCustomerId())}`,{cache:"no-store"});const d=await r.json();el.textContent=String(Array.isArray(d.orders)?d.orders.length:0)}catch{el.textContent="0"}}
function install(){const b=document.getElementById("cacho-my-orders");if(!b)return false;if(!b.dataset.d1Bound){b.dataset.d1Bound="1";b.onclick=render}updateCount();return true}
window.setInterval(install,1500);document.addEventListener("DOMContentLoaded",install);window.__cachoUpdateOrderCount=updateCount;
