const STYLE_ID = "cacho-store-tools-style";
const ORDER_STATUS_MODAL = "cacho-order-status-modal";
const ADMIN_PIN_KEY = "cacho-store-admin-pin-v1";
const statuses = ["NEW", "CONFIRMED", "PREPARING", "READY", "DELIVERED"];

function styles(){
  if(document.getElementById(STYLE_ID))return;
  const s=document.createElement("style");s.id=STYLE_ID;s.textContent=`
  .cacho-admin-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 20px;padding:6px;background:#edf4f1;border:1px solid #dce8e3;border-radius:14px;width:max-content;max-width:100%}.cacho-admin-tab{border:0;background:transparent;color:#64736e;padding:10px 15px;border-radius:9px;font-weight:800;font-size:11px;cursor:pointer;white-space:nowrap}.cacho-admin-tab.active{background:#fff;color:#0d6b62;box-shadow:0 3px 10px rgba(20,55,49,.09)}
  .cacho-tool-panel{background:#fff;border:1px solid #dfe7e3;border-radius:18px;padding:20px;box-shadow:0 6px 20px rgba(23,53,46,.06);margin-bottom:20px}.cacho-tool-head h2{margin:2px 0 5px;font-size:22px}.cacho-tool-head p{margin:0;color:#76827e;font-size:11px;line-height:1.5}.cacho-order-toolbar{display:flex;gap:9px;align-items:center;margin:15px 0;flex-wrap:wrap}.cacho-order-toolbar input{flex:1;min-width:220px;border:1px solid #d8e3df;border-radius:10px;padding:11px 12px;font:inherit;outline:none}.cacho-order-toolbar button,.cacho-password-form button{border:0;background:#0d6b62;color:#fff;border-radius:10px;padding:11px 15px;font-weight:800;cursor:pointer}.cacho-orders-list{display:grid;gap:10px}.cacho-order-card{border:1px solid #e1e8e5;border-radius:14px;padding:14px;background:#fbfcfb}.cacho-order-card-top{display:flex;justify-content:space-between;gap:15px;align-items:flex-start}.cacho-order-card strong{font-size:13px}.cacho-order-meta{font-size:10px;color:#7a8782;margin-top:4px;line-height:1.45}.cacho-status-select{border:1px solid #cddbd6;background:#eef6f3;color:#0d6b62;border-radius:999px;padding:7px 10px;font-size:10px;font-weight:850;outline:none}.cacho-order-items{margin-top:11px;padding-top:10px;border-top:1px solid #edf1ef;display:grid;gap:5px}.cacho-order-line{display:flex;justify-content:space-between;gap:10px;font-size:10px}.cacho-order-total{display:flex;justify-content:space-between;margin-top:10px;padding-top:10px;border-top:1px solid #e5ece9;font-size:11px}.cacho-empty{padding:28px;text-align:center;color:#77847f;font-size:11px}.cacho-password-form{max-width:460px;display:grid;gap:11px}.cacho-password-form label{display:grid;gap:6px;color:#44534e;font-size:11px;font-weight:800}.cacho-password-form input{border:1px solid #d8e3df;border-radius:10px;padding:11px 12px;font:inherit;outline:none}.cacho-password-msg{font-size:11px;border-radius:9px;padding:9px 11px;background:#edf8f4;color:#216b5c}.cacho-password-msg.error{background:#fff1f0;color:#a24238}
  #${ORDER_STATUS_MODAL}{position:fixed;inset:0;background:rgba(9,28,25,.58);display:flex;align-items:center;justify-content:center;padding:18px;z-index:10000;backdrop-filter:blur(5px)}.cacho-status-card{width:min(540px,100%);background:#fff;border-radius:22px;padding:24px;box-shadow:0 24px 70px rgba(0,0,0,.22);max-height:92vh;overflow:auto}.cacho-status-head{display:flex;justify-content:space-between;gap:16px}.cacho-status-head h2{margin:3px 0 5px;font-size:24px}.cacho-status-head p{margin:0;color:#75827e;font-size:12px}.cacho-status-close{border:0;background:#edf3f1;color:#50615c;border-radius:10px;width:36px;height:36px;font-size:22px;cursor:pointer}.cacho-status-form{display:flex;gap:8px;margin:18px 0}.cacho-status-form input{min-width:0;flex:1;border:1px solid #d8e3df;border-radius:10px;padding:11px 12px;outline:none;text-transform:uppercase}.cacho-status-form button{border:0;background:#0d6b62;color:#fff;border-radius:10px;padding:11px 14px;font-weight:800;cursor:pointer}.cacho-status-result{border:1px solid #dfe8e4;background:#f8fbfa;border-radius:15px;padding:16px}.cacho-status-result strong{font-size:16px;color:#173c35}.cacho-status-badge{display:inline-block;margin-top:5px;background:#0d6b62;color:#fff;padding:6px 9px;border-radius:999px;font-size:10px;font-weight:850}.cacho-status-steps{display:grid;grid-template-columns:repeat(5,1fr);gap:5px;margin-top:17px}.cacho-status-step{font-size:8px;text-align:center;color:#93a09b}.cacho-status-step .dot{width:22px;height:22px;margin:0 auto 6px;border-radius:50%;background:#e5ece9;display:grid;place-items:center;font-weight:900}.cacho-status-step.active{color:#0d6b62;font-weight:800}.cacho-status-step.active .dot{background:#0d6b62;color:#fff}.cacho-status-error{background:#fff1f0;border:1px solid #f0cbc7;color:#a24238;border-radius:10px;padding:10px;font-size:11px}.cacho-customer-status-btn{border:1px solid #dce7e3!important;background:#fff!important;color:#0d6b62!important}
  @media(max-width:760px){.cacho-admin-tabs{width:100%;overflow:auto;flex-wrap:nowrap}.cacho-admin-tab{flex:0 0 auto}.cacho-tool-panel{padding:15px}.cacho-order-card-top{flex-direction:column}.cacho-status-card{border-radius:20px;padding:18px}.cacho-status-form{flex-direction:column}.cacho-status-form button{width:100%}}
  `;document.head.appendChild(s);
}
function closeStatus(){document.getElementById(ORDER_STATUS_MODAL)?.remove();document.body.style.overflow=""}
async function checkStatus(id,result){
  result.innerHTML='<div class="cacho-status-error">Checking order status…</div>';
  try{const r=await fetch('/api/orders?orderId='+encodeURIComponent(id),{cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Order not found.');const order=d.order;const current=Math.max(0,statuses.indexOf(String(order.status||'NEW').toUpperCase()));result.innerHTML='<strong>Order #'+order.orderId+'</strong><div style="font-size:10px;color:#74817c;margin-top:3px">'+(order.customer?.name||'Customer')+'</div><span class="cacho-status-badge">'+(order.status||'NEW')+'</span><div class="cacho-status-steps">'+statuses.map((s,i)=>'<div class="cacho-status-step '+(i<=current?'active':'')+'"><div class="dot">'+(i<=current?'✓':'')+'</div>'+s+'</div>').join('')+'</div><div style="margin-top:14px;font-size:11px;color:#50605b">'+(order.items?.length||0)+' products · ₱'+Number(order.total||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})+'</div>';localStorage.setItem('cacho-last-order-v1',JSON.stringify(order))}catch(e){result.innerHTML='<div class="cacho-status-error">'+(e.message||'Unable to check status.')+'</div>'}
}
function openStatus(){styles();closeStatus();const saved=(()=>{try{return JSON.parse(localStorage.getItem('cacho-last-order-v1')||'null')}catch{return null}})();const m=document.createElement('div');m.id=ORDER_STATUS_MODAL;m.innerHTML='<div class="cacho-status-card"><div class="cacho-status-head"><div><div style="font-size:10px;font-weight:850;letter-spacing:.15em;color:#0d6b62">CACHO STORE</div><h2>Order status</h2><p>Enter your order number to see the latest progress.</p></div><button class="cacho-status-close">×</button></div><form class="cacho-status-form"><input required placeholder="CS-12345678" value="'+(saved?.orderId||'')+'"><button type="submit">Check status</button></form><div class="cacho-status-result">'+(saved?.orderId?'Checking your latest order…':'No recent order saved on this device.')+'</div></div>';document.body.appendChild(m);document.body.style.overflow='hidden';const result=m.querySelector('.cacho-status-result');m.querySelector('.cacho-status-close').onclick=closeStatus;m.onclick=e=>{if(e.target===m)closeStatus()};m.querySelector('form').onsubmit=e=>{e.preventDefault();checkStatus(e.currentTarget.querySelector('input').value.trim().toUpperCase(),result)};if(saved?.orderId)checkStatus(saved.orderId,result)}
function ordersPanel(){const p=document.createElement('section');p.className='cacho-tool-panel';p.dataset.tool='orders';p.innerHTML='<div class="cacho-tool-head"><p class="eyebrow">ORDER MANAGEMENT</p><h2>Orders</h2><p>Review incoming wholesale orders and update their fulfillment status.</p></div><div class="cacho-order-toolbar"><input placeholder="Search order number or customer…"><button type="button">Refresh</button></div><div class="cacho-orders-list"><div class="cacho-empty">Loading orders…</div></div>';return p}
async function loadOrders(p){const list=p.querySelector('.cacho-orders-list');list.innerHTML='<div class="cacho-empty">Loading orders…</div>';try{const r=await fetch('/api/orders',{cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Unable to load orders.');const q=p.querySelector('input').value.trim().toLowerCase();const orders=(d.orders||[]).filter(o=>!q||String(o.orderId).toLowerCase().includes(q)||String(o.customer?.name||'').toLowerCase().includes(q));if(!orders.length){list.innerHTML='<div class="cacho-empty">No orders found yet.</div>';return}list.innerHTML=orders.map(o=>'<article class="cacho-order-card"><div class="cacho-order-card-top"><div><strong>#'+o.orderId+'</strong><div class="cacho-order-meta">'+(o.customer?.name||'Customer')+' · '+(o.customer?.phone||'')+'<br>'+new Date(o.createdAt).toLocaleString('en-PH')+'</div></div><select class="cacho-status-select" data-id="'+o.orderId+'">'+statuses.concat('CANCELLED').map(s=>'<option '+(String(o.status||'NEW').toUpperCase()===s?'selected':'')+'>'+s+'</option>').join('')+'</select></div><div class="cacho-order-items">'+(o.items||[]).map(i=>'<div class="cacho-order-line"><span>'+i.productName+' × '+i.quantity+'</span><strong>₱'+Number(i.lineTotal||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})+'</strong></div>').join('')+'</div><div class="cacho-order-total"><span>'+(o.customer?.address||'No address supplied')+'</span><strong>₱'+Number(o.total||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})+'</strong></div></article>').join('');list.querySelectorAll('select').forEach(s=>s.onchange=async()=>{s.disabled=true;try{const r=await fetch('/api/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:s.dataset.id,status:s.value})});if(!r.ok)throw new Error('Status update failed')}catch(e){alert(e.message)}finally{s.disabled=false}})}catch(e){list.innerHTML='<div class="cacho-status-error">'+(e.message||'Unable to load orders.')+'</div>'}}
function passwordPanel(){const p=document.createElement('section');p.className='cacho-tool-panel';p.dataset.tool='password';p.hidden=true;p.innerHTML='<div class="cacho-tool-head"><p class="eyebrow">SECURITY</p><h2>Change password</h2><p>Change the owner PIN used by this browser to unlock the admin area.</p></div><form class="cacho-password-form"><label>Current PIN<input type="password" name="current" required></label><label>New PIN<input type="password" name="next" minlength="4" required></label><label>Confirm new PIN<input type="password" name="confirm" minlength="4" required></label><button type="submit">Save new PIN</button><div class="cacho-password-message" hidden></div></form>';p.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),current=String(f.get('current')||''),next=String(f.get('next')||''),confirm=String(f.get('confirm')||''),stored=localStorage.getItem(ADMIN_PIN_KEY)||'2580',msg=p.querySelector('.cacho-password-message');msg.hidden=false;msg.className='cacho-password-msg';if(current!==stored){msg.className+=' error';msg.textContent='Current PIN is incorrect.';return}if(next.length<4||next!==confirm){msg.className+=' error';msg.textContent='New PINs do not match.';return}localStorage.setItem(ADMIN_PIN_KEY,next);msg.textContent='PIN changed. Use the new PIN the next time you unlock admin.';e.currentTarget.reset()};return p}
function setupAdmin(){const a=document.querySelector('.admin-page');if(!a||a.dataset.toolsReady==='1')return;a.dataset.toolsReady='1';styles();const hero=a.querySelector('.admin-hero');if(!hero)return;const tabs=document.createElement('div');tabs.className='cacho-admin-tabs';tabs.innerHTML='<button class="cacho-admin-tab active" data-tab="pricing">Configure price</button><button class="cacho-admin-tab" data-tab="orders">Orders</button><button class="cacho-admin-tab" data-tab="password">Change password</button>';hero.after(tabs);const layout=a.querySelector('.admin-layout'),cats=a.querySelector('.categories-panel'),orders=ordersPanel(),password=passwordPanel();tabs.after(orders,password);orders.hidden=true;tabs.onclick=e=>{const b=e.target.closest('.cacho-admin-tab');if(!b)return;tabs.querySelectorAll('.cacho-admin-tab').forEach(x=>x.classList.toggle('active',x===b));const n=b.dataset.tab;if(layout)layout.hidden=n!=='pricing';if(cats)cats.hidden=n!=='pricing';orders.hidden=n!=='orders';password.hidden=n!=='password';if(n==='orders')loadOrders(orders)};orders.querySelector('button').onclick=()=>loadOrders(orders);orders.querySelector('input').oninput=()=>loadOrders(orders)}
function customerButton(){const nav=document.querySelector('.top-actions');if(!nav||nav.querySelector('.cacho-customer-status-btn'))return;const b=document.createElement('button');b.type='button';b.className='nav-btn cacho-customer-status-btn';b.textContent='Order Status';b.onclick=openStatus;nav.insertBefore(b,nav.querySelector('.cart-btn')||null)}
function boot(){styles();customerButton();setupAdmin()}
if(!window.__cachoStoreToolsInstalled){window.__cachoStoreToolsInstalled=true;new MutationObserver(boot).observe(document.body,{childList:true,subtree:true});setTimeout(boot,100)}
