const RAW_CATALOG = "https://raw.githubusercontent.com/kentcacho090-netizen/STORE/main/products.json";
const STATUSES = new Set(["NEW", "CONFIRMED", "PREPARING", "READY", "DELIVERED", "CANCELLED"]);
const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,PATCH,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type"};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json",...cors}});
async function ensureSchema(db){await db.batch([
 db.prepare(`CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL,unit TEXT NOT NULL,price REAL NOT NULL DEFAULT 0,stock INTEGER NOT NULL DEFAULT 0,image TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL)`),
 db.prepare(`CREATE TABLE IF NOT EXISTS orders(order_id TEXT PRIMARY KEY,customer_id TEXT NOT NULL,customer_name TEXT NOT NULL,phone TEXT NOT NULL,address TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',total REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'NEW',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),
 db.prepare(`CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT NOT NULL,product_id INTEGER NOT NULL,product_name TEXT NOT NULL,category TEXT NOT NULL,unit TEXT NOT NULL,quantity INTEGER NOT NULL,wholesale_price REAL NOT NULL,line_total REAL NOT NULL)`),
 db.prepare(`CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id)`),
 db.prepare(`CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id)`)
]);}
function normalizeProduct(p){return{id:Number(p?.id),name:String(p?.name||"Product").trim(),category:String(p?.category||"Other").trim()||"Other",unit:String(p?.unit||"Each").trim()||"Each",price:Math.max(0,Number(p?.price||0)),stock:Math.max(0,Math.floor(Number(p?.stock||0))),image:String(p?.image||""),active:p?.active!==false};}
async function seedProducts(db){const count=await db.prepare("SELECT COUNT(*) AS count FROM products").first("count");if(Number(count||0)>0)return;const r=await fetch(RAW_CATALOG,{cf:{cacheTtl:0,cacheEverything:false}});if(!r.ok)throw new Error("Unable to load the existing catalog for D1 seeding.");const d=await r.json();const ps=(Array.isArray(d?.products)?d.products:[]).map(normalizeProduct).filter(p=>Number.isFinite(p.id)&&p.name);const now=new Date().toISOString();for(let i=0;i<ps.length;i+=50)await db.batch(ps.slice(i,i+50).map(p=>db.prepare("INSERT OR REPLACE INTO products(id,name,category,unit,price,stock,image,active,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(p.id,p.name,p.category,p.unit,p.price,p.stock,p.image,p.active?1:0,now)));}
async function productsResponse(env){await ensureSchema(env.DB);await seedProducts(env.DB);const r=await env.DB.prepare("SELECT id,name,category,unit,price,stock,image,active FROM products WHERE active=1 ORDER BY category,name").all();const products=(r.results||[]).map(p=>({...p,active:Boolean(p.active)}));return json({products,categories:[...new Set(products.map(p=>p.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b))});}
async function listOrders(env,customerId){if(!customerId)return json({error:"customerId is required."},400);await ensureSchema(env.DB);const r=await env.DB.prepare("SELECT * FROM orders WHERE customer_id=? ORDER BY created_at DESC").bind(customerId).all();const out=[];for(const o of r.results||[]){const items=await env.DB.prepare("SELECT product_id AS productId,product_name AS productName,category,unit,quantity,wholesale_price AS wholesalePrice,line_total AS lineTotal FROM order_items WHERE order_id=? ORDER BY id").bind(o.order_id).all();out.push({orderId:o.order_id,customerId:o.customer_id,customer:{name:o.customer_name,phone:o.phone,address:o.address,notes:o.notes},total:o.total,status:o.status,createdAt:o.created_at,updatedAt:o.updated_at,items:items.results||[]});}return json({orders:out});}
async function createOrder(env,body){await ensureSchema(env.DB);await seedProducts(env.DB);const customerId=String(body?.customerId||"").trim(),customer=body?.customer||{},name=String(customer.name||"").trim(),phone=String(customer.phone||"").trim(),address=String(customer.address||"").trim(),notes=String(customer.notes||"").trim(),items=Array.isArray(body?.items)?body.items:[];if(!customerId||!name||!phone||!items.length)throw new Error("Customer ID, name, phone, and at least one item are required.");const validated=[];let total=0;for(const raw of items){const productId=Number(raw?.productId),quantity=Math.floor(Number(raw?.quantity));if(!Number.isFinite(productId)||quantity<=0)continue;const p=await env.DB.prepare("SELECT id,name,category,unit,price,stock,active FROM products WHERE id=?").bind(productId).first();if(!p||!p.active)throw new Error(`${raw?.productName||productId} is unavailable.`);if(quantity>Number(p.stock))throw new Error(`${p.name} only has ${p.stock} left.`);const lineTotal=Number(p.price)*quantity;validated.push({product:p,quantity,lineTotal});total+=lineTotal;}if(!validated.length)throw new Error("No valid items were found in the order.");const orderId=`CS-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`,now=new Date().toISOString();const statements=[env.DB.prepare("INSERT INTO orders(order_id,customer_id,customer_name,phone,address,notes,total,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(orderId,customerId,name,phone,address,notes,total,"NEW",now,now)];for(const i of validated){statements.push(env.DB.prepare("INSERT INTO order_items(order_id,product_id,product_name,category,unit,quantity,wholesale_price,line_total) VALUES(?,?,?,?,?,?,?,?)").bind(orderId,i.product.id,i.product.name,i.product.category,i.product.unit,i.quantity,i.product.price,i.lineTotal));statements.push(env.DB.prepare("UPDATE products SET stock=stock-?,updated_at=? WHERE id=? AND stock>=?").bind(i.quantity,now,i.product.id,i.quantity));}await env.DB.batch(statements);return json({ok:true,order:{orderId,customerId,customer:{name,phone,address,notes},total,status:"NEW",createdAt:now,updatedAt:now,items:validated.map(i=>({productId:i.product.id,productName:i.product.name,category:i.product.category,unit:i.product.unit,quantity:i.quantity,wholesalePrice:i.product.price,lineTotal:i.lineTotal}))}},201);}
async function updateOrder(env,id,body){await ensureSchema(env.DB);const status=String(body?.status||"").toUpperCase();if(!STATUSES.has(status))return json({error:"Invalid order status."},400);const now=new Date().toISOString(),r=await env.DB.prepare("UPDATE orders SET status=?,updated_at=? WHERE order_id=?").bind(status,now,id).run();return r.meta?.changes?json({ok:true,orderId:id,status,updatedAt:now}):json({error:"Order not found."},404);}
async function deleteOrder(env,id){await ensureSchema(env.DB);const o=await env.DB.prepare("SELECT status FROM orders WHERE order_id=?").bind(id).first();if(!o)return json({error:"Order not found."},404);if(!["DELIVERED","CANCELLED"].includes(o.status))return json({error:"Only delivered or cancelled orders can be removed."},400);await env.DB.batch([env.DB.prepare("DELETE FROM order_items WHERE order_id=?").bind(id),env.DB.prepare("DELETE FROM orders WHERE order_id=?").bind(id)]);return json({ok:true});}
export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors});const url=new URL(request.url);try{if(url.pathname==="/api/products"&&request.method==="GET")return productsResponse(env);if(url.pathname==="/api/orders"&&request.method==="GET")return listOrders(env,url.searchParams.get("customerId"));if(url.pathname==="/api/orders"&&request.method==="POST")return createOrder(env,await request.json());if(url.pathname.startsWith("/api/orders/")&&request.method==="PATCH")return updateOrder(env,url.pathname.split("/").pop(),await request.json());if(url.pathname.startsWith("/api/orders/")&&request.method==="DELETE")return deleteOrder(env,url.pathname.split("/").pop());return env.ASSETS.fetch(request);}catch(e){return json({error:e?.message||"Request failed."},500);}}};
